"""Add analytics tables

Revision ID: 0002
Revises: 0001
Create Date: 2025-01-01 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create user_sessions table
    op.create_table('user_sessions',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('session_id', sa.String(length=255), nullable=False),
        sa.Column('user_id', sa.String(length=255), nullable=True),
        sa.Column('ip_address', sa.String(length=45), nullable=True),
        sa.Column('user_agent', sa.Text(), nullable=True),
        sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('metadata', sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_sessions_session_id', 'user_sessions', ['session_id'], unique=False)
    op.create_index('idx_user_sessions_user_id', 'user_sessions', ['user_id'], unique=False)
    op.create_index('idx_user_sessions_started_at', 'user_sessions', ['started_at'], unique=False)
    
    # Create user_interactions table
    op.create_table('user_interactions',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('session_id', sa.String(length=255), nullable=False),
        sa.Column('conversation_id', sa.String(length=255), nullable=False),
        sa.Column('interaction_type', sa.String(length=50), nullable=False),
        sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
        sa.Column('message_content', sa.Text(), nullable=True),
        sa.Column('message_length', sa.Integer(), nullable=True),
        sa.Column('model_used', sa.String(length=100), nullable=True),
        sa.Column('response_time_ms', sa.Integer(), nullable=True),
        sa.Column('response_length', sa.Integer(), nullable=True),
        sa.Column('error_type', sa.String(length=100), nullable=True),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('metadata', sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_interactions_session_id', 'user_interactions', ['session_id'], unique=False)
    op.create_index('idx_user_interactions_conversation_id', 'user_interactions', ['conversation_id'], unique=False)
    op.create_index('idx_user_interactions_type', 'user_interactions', ['interaction_type'], unique=False)
    op.create_index('idx_user_interactions_timestamp', 'user_interactions', ['timestamp'], unique=False)
    op.create_index('idx_user_interactions_model', 'user_interactions', ['model_used'], unique=False)
    
    # Create conversation_metrics table
    op.create_table('conversation_metrics',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('conversation_id', sa.String(length=255), nullable=False),
        sa.Column('session_id', sa.String(length=255), nullable=False),
        sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('total_messages', sa.Integer(), nullable=False),
        sa.Column('user_messages', sa.Integer(), nullable=False),
        sa.Column('assistant_messages', sa.Integer(), nullable=False),
        sa.Column('total_user_characters', sa.Integer(), nullable=False),
        sa.Column('total_assistant_characters', sa.Integer(), nullable=False),
        sa.Column('average_user_message_length', sa.Float(), nullable=False),
        sa.Column('average_assistant_message_length', sa.Float(), nullable=False),
        sa.Column('total_duration_seconds', sa.Float(), nullable=True),
        sa.Column('average_response_time_ms', sa.Float(), nullable=True),
        sa.Column('models_used', sa.JSON(), nullable=False),
        sa.Column('primary_model', sa.String(length=100), nullable=True),
        sa.Column('rag_used', sa.Boolean(), nullable=False),
        sa.Column('streaming_used', sa.Boolean(), nullable=False),
        sa.Column('error_count', sa.Integer(), nullable=False),
        sa.Column('feedback_score', sa.Float(), nullable=True),
        sa.Column('metadata', sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('conversation_id')
    )
    op.create_index('idx_conversation_metrics_conversation_id', 'conversation_metrics', ['conversation_id'], unique=False)
    op.create_index('idx_conversation_metrics_session_id', 'conversation_metrics', ['session_id'], unique=False)
    op.create_index('idx_conversation_metrics_started_at', 'conversation_metrics', ['started_at'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_conversation_metrics_started_at', table_name='conversation_metrics')
    op.drop_index('idx_conversation_metrics_session_id', table_name='conversation_metrics')
    op.drop_index('idx_conversation_metrics_conversation_id', table_name='conversation_metrics')
    op.drop_table('conversation_metrics')
    op.drop_index('idx_user_interactions_model', table_name='user_interactions')
    op.drop_index('idx_user_interactions_timestamp', table_name='user_interactions')
    op.drop_index('idx_user_interactions_type', table_name='user_interactions')
    op.drop_index('idx_user_interactions_conversation_id', table_name='user_interactions')
    op.drop_index('idx_user_interactions_session_id', table_name='user_interactions')
    op.drop_table('user_interactions')
    op.drop_index('idx_user_sessions_started_at', table_name='user_sessions')
    op.drop_index('idx_user_sessions_user_id', table_name='user_sessions')
    op.drop_index('idx_user_sessions_session_id', table_name='user_sessions')
    op.drop_table('user_sessions')
    # ### end Alembic commands ###
