import {
  Button,
  Callout,
  Card,
  CardBody,
  CardHeader,
  Divider,
  H1,
  H2,
  Pill,
  Row,
  Stack,
  Stat,
  Table,
  Text,
  useCanvasAction,
  useHostTheme,
} from "cursor/canvas";

type QueueStatus = "done" | "next" | "queued" | "later";

type PlanRef = {
  label: string;
  /** Workspace-relative path under viletech-platform */
  path: string;
};

type QueueRow = {
  order: string;
  item: string;
  plans: PlanRef[];
  status: QueueStatus;
  note: string;
};

// Generated by vdp/scripts/sync-handoff-queue-canvas.py — do not edit statuses by hand.
// Source: .cursor/handoff/очередь-компромисс-2026-09-26/queue.json + plan frontmatter todos. Synced: 2026-09-27.

const QUEUE: QueueRow[] = [
  {
    order: "1",
    item: "UAT F1 API / session",
    plans: [
      {
        label: "uat_f1",
        path: ".cursor/plans/uat_f1_api_session.plan.md",
      }
    ],
    status: "done",
    note: "Done (ci-pr-pilot); alpha feedback 2026-09-27 пункт 1",
  },
  {
    order: "2",
    item: "UAT F2 submit without docs disabled",
    plans: [
      {
        label: "uat_f2",
        path: ".cursor/plans/uat_f2_submit_docs.plan.md",
      }
    ],
    status: "next",
    note: "Next; пункт 2",
  },
  {
    order: "3",
    item: "UAT F3 counterparty verify",
    plans: [
      {
        label: "uat_f3",
        path: ".cursor/plans/uat_f3_cp_verify.plan.md",
      }
    ],
    status: "queued",
    note: "Пункт 3 + 3.1",
  },
  {
    order: "4",
    item: "UAT F4 delete confirm",
    plans: [
      {
        label: "uat_f4",
        path: ".cursor/plans/uat_f4_delete_confirm.plan.md",
      }
    ],
    status: "queued",
    note: "Пункт 4",
  },
  {
    order: "5",
    item: "UAT F5 no dashes",
    plans: [
      {
        label: "uat_f5",
        path: ".cursor/plans/uat_f5_no_dashes.plan.md",
      }
    ],
    status: "queued",
    note: "Пункт 5",
  },
  {
    order: "6",
    item: "UAT F6 receipt CTA copy",
    plans: [
      {
        label: "uat_f6",
        path: ".cursor/plans/uat_f6_receipt_cta.plan.md",
      }
    ],
    status: "queued",
    note: "Пункт 6",
  },
  {
    order: "7",
    item: "UAT F7 provider closed forms",
    plans: [
      {
        label: "uat_f7",
        path: ".cursor/plans/uat_f7_provider_closed.plan.md",
      }
    ],
    status: "queued",
    note: "Пункт 7",
  },
  {
    order: "—",
    item: "UAT W7 browser ladders",
    plans: [
      {
        label: "uat_w7",
        path: ".cursor/plans/архив/uat_w7_browser_ladders_return.plan.md",
      }
    ],
    status: "later",
    note: "План в архиве; после F1–F7",
  },
  {
    order: "—",
    item: "Stage B (B1→B3)",
    plans: [
      {
        label: "b1_golden",
        path: ".cursor/plans/архив/api_contract_b1_golden.plan.md",
      },
      {
        label: "b2_vitest",
        path: ".cursor/plans/архив/api_contract_b2_vitest.plan.md",
      },
      {
        label: "b3_docs_qg",
        path: ".cursor/plans/архив/api_contract_b3_docs_qg.plan.md",
      }
    ],
    status: "later",
    note: "Планы в архиве",
  },
  {
    order: "—",
    item: "Ops / alpha deploy",
    plans: [
      {
        label: "blockers_and_deploy",
        path: ".cursor/plans/архив/vdp_blockers_and_deploy_99106aff.plan.md",
      }
    ],
    status: "later",
    note: "План в архиве",
  },
];

function PlanOpenButtons({ plans }: { plans: PlanRef[] }) {
  const dispatch = useCanvasAction();
  return (
    <Stack gap={4}>
      {plans.map((plan) => (
        <Button
          key={plan.path}
          variant="ghost"
          onClick={() => dispatch({ type: "openFile", path: plan.path })}
        >
          {plan.label}
        </Button>
      ))}
    </Stack>
  );
}

function statusTone(
  status: QueueStatus,
): "neutral" | "info" | "success" | "warning" {
  switch (status) {
    case "done":
      return "success";
    case "next":
      return "info";
    case "queued":
      return "neutral";
    case "later":
      return "warning";
  }
}

function statusLabel(status: QueueStatus): string {
  switch (status) {
    case "done":
      return "done";
    case "next":
      return "next";
    case "queued":
      return "queued";
    case "later":
      return "later";
  }
}

export default function HandoffQueue() {
  const theme = useHostTheme();
  const dispatch = useCanvasAction();

  return (
    <Stack gap={20} style={{ padding: 20, maxWidth: 960 }}>
      <Stack gap={6}>
        <H1>Handoff: очередь</H1>
        <Text tone="secondary" size="small">
          Источник: .cursor/handoff/очередь-компромисс-2026-09-26 · chat ac80db37 · sync 2026-09-27
        </Text>
      </Stack>

      <Callout tone="info">
        Статусы из frontmatter todos планов (completed/cancelled = done). После
        закрытия плана: make -C vdp sync-handoff-queue. Next: UAT F2 submit without docs disabled.
      </Callout>

      <Row gap={12} wrap>
        <Stat value={"done"} label={"UAT F1 API / session"} tone="success" />
        <Stat value={"—"} label={"—"} tone="success" />
        <Stat value={"UAT F2 submit without docs disabled"} label="Next implement" tone="info" />
      </Row>

      <Card>
        <CardHeader
          trailing={
            <Button
              variant="ghost"
              onClick={() =>
                dispatch({
                  type: "openFile",
                  path: ".cursor/plans/api_contract_lean_master.plan.md",
                })
              }
            >
              lean master Stage A
            </Button>
          }
        >
          Ежедневная очередь
        </CardHeader>
        <CardBody style={{ padding: 0 }}>
          <Table
            headers={["#", "Работа", "План", "Статус", "Заметка"]}
            rows={QUEUE.map((row) => [
              row.order,
              row.item,
              <PlanOpenButtons key={row.item} plans={row.plans} />,
              <Pill key={`${row.item}-status`} tone={statusTone(row.status)} size="sm">
                {statusLabel(row.status)}
              </Pill>,
              row.note,
            ])}
            rowTone={QUEUE.map((row) =>
              row.status === "next" ? "info" : undefined,
            )}
          />
        </CardBody>
      </Card>

      <Divider />

      <Stack gap={8}>
        <H2>Файлы handoff</H2>
        <Text style={{ color: theme.text.secondary }}>
          README и queue.json в репо; canvas обновляется скриптом sync.
        </Text>
        <Stack gap={4}>
          <Button
            variant="ghost"
            onClick={() =>
              dispatch({
                type: "openFile",
                path: ".cursor/handoff/очередь-компромисс-2026-09-26/README.md",
              })
            }
          >
            handoff README
          </Button>
          <Button
            variant="ghost"
            onClick={() =>
              dispatch({
                type: "openFile",
                path: ".cursor/handoff/очередь-компромисс-2026-09-26/queue.json",
              })
            }
          >
            queue.json
          </Button>
          <Button
            variant="ghost"
            onClick={() =>
              dispatch({
                type: "openFile",
                path: ".cursor/plans/live_backlog_after_status_sync.plan.md",
              })
            }
          >
            live_backlog_after_status_sync
          </Button>
        </Stack>
      </Stack>
    </Stack>
  );
}
