import {
  Button,
  Callout,
  Card,
  CardBody,
  CardHeader,
  Divider,
  H1,
  H2,
  Pill,
  Row,
  Stack,
  Stat,
  Table,
  Text,
  useCanvasAction,
  useHostTheme,
} from "cursor/canvas";

type QueueStatus = "done" | "next" | "queued" | "later";

type PlanRef = {
  label: string;
  /** Workspace-relative path under viletech-platform */
  path: string;
};

type QueueRow = {
  order: string;
  item: string;
  plans: PlanRef[];
  status: QueueStatus;
  note: string;
};

// Generated by vdp/scripts/sync-handoff-queue-canvas.py — do not edit statuses by hand.
// Source: .cursor/handoff/очередь-компромисс-2026-09-26/queue.json + plan frontmatter todos. Synced: 2026-09-26.

const QUEUE: QueueRow[] = [
  {
    order: "—",
    item: "A1 — forms.yaml schemas",
    plans: [
      {
        label: "a1_forms_yaml",
        path: ".cursor/plans/api_contract_a1_forms_yaml.plan.md",
      }
    ],
    status: "done",
    note: "Form + $ref на 4 path’а в forms.yaml",
  },
  {
    order: "1",
    item: "Карточка, п.14",
    plans: [
      {
        label: "карточка_без_прочерков",
        path: ".cursor/plans/карточка_без_прочерков_e874f6dc.plan.md",
      }
    ],
    status: "done",
    note: "Участники без прочерков + gate",
  },
  {
    order: "2",
    item: "A2 — schema helper",
    plans: [
      {
        label: "a2_schema_helper",
        path: ".cursor/plans/api_contract_a2_schema_helper.plan.md",
      }
    ],
    status: "done",
    note: "Load / ValidateNamedSchema",
  },
  {
    order: "3",
    item: "A3 — httptest",
    plans: [
      {
        label: "a3_httptest",
        path: ".cursor/plans/api_contract_a3_httptest.plan.md",
      }
    ],
    status: "done",
    note: "health + create/get/action Form assert",
  },
  {
    order: "4",
    item: "A4 — docs QG Stage A",
    plans: [
      {
        label: "a4_docs_qg",
        path: ".cursor/plans/api_contract_a4_docs_qg.plan.md",
      }
    ],
    status: "next",
    note: "Закрытие Stage A",
  },
  {
    order: "5",
    item: "UAT W2 parties hygiene",
    plans: [
      {
        label: "uat_w2",
        path: ".cursor/plans/uat_w2_parties_hygiene.plan.md",
      }
    ],
    status: "queued",
    note: "Сначала repro в браузере",
  },
  {
    order: "6",
    item: "UAT W4 card field labels",
    plans: [
      {
        label: "uat_w4",
        path: ".cursor/plans/uat_w4_card_field_labels.plan.md",
      }
    ],
    status: "queued",
    note: "Сначала repro",
  },
  {
    order: "7",
    item: "UAT W5 root cancel",
    plans: [
      {
        label: "uat_w5",
        path: ".cursor/plans/uat_w5_root_cancel.plan.md",
      }
    ],
    status: "queued",
    note: "Сначала repro",
  },
  {
    order: "—",
    item: "UAT W7 browser ladders",
    plans: [
      {
        label: "uat_w7",
        path: ".cursor/plans/uat_w7_browser_ladders_return.plan.md",
      }
    ],
    status: "later",
    note: "Отдельный день",
  },
  {
    order: "—",
    item: "Stage B (B1→B3)",
    plans: [
      {
        label: "b1_golden",
        path: ".cursor/plans/api_contract_b1_golden.plan.md",
      },
      {
        label: "b2_vitest",
        path: ".cursor/plans/api_contract_b2_vitest.plan.md",
      },
      {
        label: "b3_docs_qg",
        path: ".cursor/plans/api_contract_b3_docs_qg.plan.md",
      }
    ],
    status: "later",
    note: "После Stage A, по желанию",
  },
  {
    order: "—",
    item: "Ops / alpha deploy",
    plans: [
      {
        label: "blockers_and_deploy",
        path: ".cursor/plans/vdp_blockers_and_deploy_99106aff.plan.md",
      }
    ],
    status: "later",
    note: "Не в ежедневной очереди",
  },
];

function PlanOpenButtons({ plans }: { plans: PlanRef[] }) {
  const dispatch = useCanvasAction();
  return (
    <Stack gap={4}>
      {plans.map((plan) => (
        <Button
          key={plan.path}
          variant="ghost"
          onClick={() => dispatch({ type: "openFile", path: plan.path })}
        >
          {plan.label}
        </Button>
      ))}
    </Stack>
  );
}

function statusTone(
  status: QueueStatus,
): "neutral" | "info" | "success" | "warning" {
  switch (status) {
    case "done":
      return "success";
    case "next":
      return "info";
    case "queued":
      return "neutral";
    case "later":
      return "warning";
  }
}

function statusLabel(status: QueueStatus): string {
  switch (status) {
    case "done":
      return "done";
    case "next":
      return "next";
    case "queued":
      return "queued";
    case "later":
      return "later";
  }
}

export default function HandoffQueue() {
  const theme = useHostTheme();
  const dispatch = useCanvasAction();

  return (
    <Stack gap={20} style={{ padding: 20, maxWidth: 960 }}>
      <Stack gap={6}>
        <H1>Handoff: очередь</H1>
        <Text tone="secondary" size="small">
          Источник: .cursor/handoff/очередь-компромисс-2026-09-26 · chat ac80db37 · sync 2026-09-26
        </Text>
      </Stack>

      <Callout tone="info">
        Статусы из frontmatter todos планов (completed/cancelled = done). После
        закрытия плана: make -C vdp sync-handoff-queue. Next: A4 — docs QG Stage A.
      </Callout>

      <Row gap={12} wrap>
        <Stat value={"done"} label={"A2 schema helper"} tone="success" />
        <Stat value={"done"} label={"A3 httptest"} tone="success" />
        <Stat value={"A4"} label="Next implement" tone="info" />
      </Row>

      <Card>
        <CardHeader
          trailing={
            <Button
              variant="ghost"
              onClick={() =>
                dispatch({
                  type: "openFile",
                  path: ".cursor/plans/api_contract_lean_master.plan.md",
                })
              }
            >
              lean master Stage A
            </Button>
          }
        >
          Ежедневная очередь
        </CardHeader>
        <CardBody style={{ padding: 0 }}>
          <Table
            headers={["#", "Работа", "План", "Статус", "Заметка"]}
            rows={QUEUE.map((row) => [
              row.order,
              row.item,
              <PlanOpenButtons key={row.item} plans={row.plans} />,
              <Pill key={`${row.item}-status`} tone={statusTone(row.status)} size="sm">
                {statusLabel(row.status)}
              </Pill>,
              row.note,
            ])}
            rowTone={QUEUE.map((row) =>
              row.status === "next" ? "info" : undefined,
            )}
          />
        </CardBody>
      </Card>

      <Divider />

      <Stack gap={8}>
        <H2>Файлы handoff</H2>
        <Text style={{ color: theme.text.secondary }}>
          README и queue.json в репо; canvas обновляется скриптом sync.
        </Text>
        <Stack gap={4}>
          <Button
            variant="ghost"
            onClick={() =>
              dispatch({
                type: "openFile",
                path: ".cursor/handoff/очередь-компромисс-2026-09-26/README.md",
              })
            }
          >
            handoff README
          </Button>
          <Button
            variant="ghost"
            onClick={() =>
              dispatch({
                type: "openFile",
                path: ".cursor/handoff/очередь-компромисс-2026-09-26/queue.json",
              })
            }
          >
            queue.json
          </Button>
          <Button
            variant="ghost"
            onClick={() =>
              dispatch({
                type: "openFile",
                path: ".cursor/plans/live_backlog_after_status_sync.plan.md",
              })
            }
          >
            live_backlog_after_status_sync
          </Button>
        </Stack>
      </Stack>
    </Stack>
  );
}
