#!/usr/bin/env bash
# One-shot host preparation for VDP Compose CD (Ubuntu 22.04/24.04, run as root).
#
# Installs Docker CE, creates the unprivileged deploy user, generates host secrets,
# and puts Caddy in front of fe-prod so the environment is reachable over HTTPS.
#
# Usage:
#   DEPLOY_PUBKEY="ssh-ed25519 AAAA... vdp-deploy" \
#   VDP_DOMAIN=alpha.vedy.io \
#   bash bootstrap-host.sh
set -euo pipefail

DEPLOY_USER="${DEPLOY_USER:-deploy}"
DEPLOY_PATH="${DEPLOY_PATH:-/opt/vdp}"
VDP_DOMAIN="${VDP_DOMAIN:-}"
DEPLOY_PUBKEY="${DEPLOY_PUBKEY:-}"
ENVIRONMENT="${ENVIRONMENT:-alpha}"

if [ "$(id -u)" -ne 0 ]; then
  echo "run as root: sudo -i, then re-run" >&2
  exit 1
fi

if [ -z "$DEPLOY_PUBKEY" ]; then
  echo "DEPLOY_PUBKEY is required (contents of vdp_deploy_ed25519.pub)" >&2
  exit 1
fi

echo "==> [1/6] Docker CE from the official repository"
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y -qq ca-certificates curl gnupg rsync ufw
install -m 0755 -d /etc/apt/keyrings
if [ ! -f /etc/apt/keyrings/docker.asc ]; then
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
  chmod a+r /etc/apt/keyrings/docker.asc
fi
. /etc/os-release
# Docker publishes per-codename repos and lags behind brand-new Ubuntu releases,
# so fall back to the newest codename Docker actually serves.
DOCKER_SUITE="$VERSION_CODENAME"
if ! curl -fsSL -o /dev/null "https://download.docker.com/linux/ubuntu/dists/${DOCKER_SUITE}/Release"; then
  for candidate in noble jammy; do
    if curl -fsSL -o /dev/null "https://download.docker.com/linux/ubuntu/dists/${candidate}/Release"; then
      echo "    Docker has no repo for '${VERSION_CODENAME}', using '${candidate}'"
      DOCKER_SUITE="$candidate"
      break
    fi
  done
fi
cat >/etc/apt/sources.list.d/docker.list <<EOF
deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu ${DOCKER_SUITE} stable
EOF
apt-get update -qq
if ! apt-get install -y -qq docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin; then
  echo "    Docker CE repo failed, falling back to Ubuntu-packaged docker.io + compose v2"
  rm -f /etc/apt/sources.list.d/docker.list
  apt-get update -qq
  apt-get install -y -qq docker.io docker-compose-v2 docker-buildx
fi
systemctl enable --now docker
docker compose version

echo "==> [2/6] deploy user ${DEPLOY_USER}"
if ! id -u "$DEPLOY_USER" >/dev/null 2>&1; then
  adduser --disabled-password --gecos "VDP deploy" "$DEPLOY_USER"
fi
usermod -aG docker "$DEPLOY_USER"
install -d -m 0700 -o "$DEPLOY_USER" -g "$DEPLOY_USER" "/home/${DEPLOY_USER}/.ssh"
touch "/home/${DEPLOY_USER}/.ssh/authorized_keys"
grep -qxF "$DEPLOY_PUBKEY" "/home/${DEPLOY_USER}/.ssh/authorized_keys" \
  || echo "$DEPLOY_PUBKEY" >> "/home/${DEPLOY_USER}/.ssh/authorized_keys"
chmod 0600 "/home/${DEPLOY_USER}/.ssh/authorized_keys"
chown -R "${DEPLOY_USER}:${DEPLOY_USER}" "/home/${DEPLOY_USER}/.ssh"

echo "==> [3/6] ${DEPLOY_PATH}"
install -d -m 0755 -o "$DEPLOY_USER" -g "$DEPLOY_USER" "$DEPLOY_PATH"

echo "==> [4/6] host secrets ${DEPLOY_PATH}/.env.deploy"
ENV_FILE="${DEPLOY_PATH}/.env.deploy"
if [ -f "$ENV_FILE" ]; then
  echo "    exists, keeping current secrets"
else
  cat >"$ENV_FILE" <<EOF
# Generated by bootstrap-host.sh — host-only secrets, never commit.
ENVIRONMENT=${ENVIRONMENT}
JWT_SECRET=$(openssl rand -hex 32)
HUB_SHARED_SECRET=$(openssl rand -hex 32)
GATEWAY_RATE_LIMIT=2000

# Keep application ports on loopback; Caddy terminates TLS and proxies.
FE_PROD_BIND=127.0.0.1
CORE_BIND=127.0.0.1
HUB_BIND=127.0.0.1
DOCS_BIND=127.0.0.1
DB_BIND=127.0.0.1
EOF
  chown "${DEPLOY_USER}:${DEPLOY_USER}" "$ENV_FILE"
  chmod 0600 "$ENV_FILE"
  echo "    generated fresh random secrets"
fi

echo "==> [5/6] firewall (22/80/443 only)"
ufw allow 22/tcp >/dev/null
ufw allow 80/tcp >/dev/null
ufw allow 443/tcp >/dev/null
ufw --force enable >/dev/null
ufw status numbered

echo "==> [6/6] Caddy reverse proxy"
if [ -z "$VDP_DOMAIN" ]; then
  echo "    VDP_DOMAIN not set — skipping Caddy. Re-run with VDP_DOMAIN=alpha.example.com once DNS resolves."
else
  if ! command -v caddy >/dev/null 2>&1; then
    apt-get install -y -qq debian-keyring debian-archive-keyring apt-transport-https
    curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' \
      | gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
    curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' \
      > /etc/apt/sources.list.d/caddy-stable.list
    apt-get update -qq
    apt-get install -y -qq caddy
  fi
  cat >/etc/caddy/Caddyfile <<EOF
${VDP_DOMAIN} {
	encode zstd gzip

	# API and BFF calls go straight to core; everything else is the SSR frontend.
	handle /api/* {
		reverse_proxy 127.0.0.1:8080
	}

	handle {
		reverse_proxy 127.0.0.1:3000
	}

	log {
		output file /var/log/caddy/${VDP_DOMAIN}.log
	}
}

import /etc/caddy/preview.d/*
EOF
  install -d -m 0755 -o caddy -g caddy /var/log/caddy
  install -d -m 0755 /etc/caddy/preview.d
  printf '# preview site snippets from deploy-preview.sh\n' > /etc/caddy/preview.d/.keep.caddy
  caddy validate --config /etc/caddy/Caddyfile
  systemctl enable --now caddy
  systemctl reload caddy || systemctl restart caddy
  echo "    Caddy serving ${VDP_DOMAIN} (certificate issues on first HTTPS request)"
fi

echo "==> [7/7] systemd: compose autostart + uptime timer"
install -d -m 0755 -o "$DEPLOY_USER" -g "$DEPLOY_USER" "${DEPLOY_PATH}/ops/systemd" "${DEPLOY_PATH}/scripts"
install -d -m 0755 /var/lib/vdp-uptime
chown "${DEPLOY_USER}:${DEPLOY_USER}" /var/lib/vdp-uptime
if [ -f "${DEPLOY_PATH}/ops/systemd/vdp.service" ]; then
  install -m 0644 "${DEPLOY_PATH}/ops/systemd/vdp.service" /etc/systemd/system/vdp.service
  install -m 0644 "${DEPLOY_PATH}/ops/systemd/vdp-uptime.service" /etc/systemd/system/vdp-uptime.service
  install -m 0644 "${DEPLOY_PATH}/ops/systemd/vdp-uptime.timer" /etc/systemd/system/vdp-uptime.timer
  systemctl daemon-reload
  systemctl enable vdp.service
  systemctl enable --now vdp-uptime.timer
  echo "    enabled vdp.service + vdp-uptime.timer"
  echo "    create ${DEPLOY_PATH}/.env.uptime (UPTIME_BOT_TOKEN, UPTIME_CHAT_ID) for Telegram alerts"
else
  echo "    skip: copy ops/systemd/* into ${DEPLOY_PATH} then re-run this block"
fi

cat <<EOF

Host is ready.
  deploy user : ${DEPLOY_USER}
  deploy path : ${DEPLOY_PATH}
  secrets     : ${DEPLOY_PATH}/.env.deploy (0600, host-only)
  domain      : ${VDP_DOMAIN:-<not configured>}
  autostart   : systemctl enable vdp.service (compose up after reboot)
  uptime      : vdp-uptime.timer → Telegram (@vdp_uptime_bot)

GitHub Environment secrets to set:
  DEPLOY_HOST = $(curl -fsS --max-time 5 https://api.ipify.org 2>/dev/null || echo '<server public ip>')
  DEPLOY_USER = ${DEPLOY_USER}
  DEPLOY_PATH = ${DEPLOY_PATH}
  DEPLOY_SSH_KEY = contents of the private key vdp_deploy_ed25519
EOF
