-- R4 docs domain extensions

ALTER TABLE counterparties ADD COLUMN IF NOT EXISTS created_by TEXT;
ALTER TABLE counterparties ADD COLUMN IF NOT EXISTS form_payment_ids TEXT;
ALTER TABLE counterparties ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

ALTER TABLE comments ADD COLUMN IF NOT EXISTS kind TEXT NOT NULL DEFAULT 'external';
ALTER TABLE comments ADD COLUMN IF NOT EXISTS file_ids TEXT;

ALTER TABLE files ADD COLUMN IF NOT EXISTS size_bytes BIGINT NOT NULL DEFAULT 0;
