"""Pydantic schemas for request/response validation"""

from app.database.schemas.knowledge_source import (
    KnowledgeSourceBase,
    KnowledgeSourceCreate,
    KnowledgeSourceUpdate,
    KnowledgeSourceResponse,
    KnowledgeSourceList,
    KnowledgeChunkResponse,
    KnowledgeSourceUpload,
)

from app.database.schemas.document import (
    PaymentDocumentBase,
    PaymentDocumentCreate,
    PaymentDocumentUpdate,
    PaymentDocumentResponse,
    PaymentDocumentList,
    DocumentUploadResponse,
    AnalysisResultBase,
    AnalysisResultCreate,
    AnalysisResultResponse,
    DocumentAnalysisRequest,
    DocumentAnalysisResponse,
    DocumentListFilters,
)

from app.database.schemas.compliance import (
    ComplianceCheckBase,
    ComplianceCheckCreate,
    ComplianceCheckResponse,
    ComplianceCheckRequest,
    ComplianceCheckItem,
    ComplianceCheckResult,
    ComplianceCheckListResponse,
    ComplianceKnowledgeBase,
    ComplianceKnowledgeCreate,
    ComplianceStatistics,
)

from app.database.schemas.risk import (
    RiskAssessmentBase,
    RiskAssessmentCreate,
    RiskAssessmentResponse,
    RiskAssessmentRequest,
    RiskFactor,
    EconomicIndex,
    RiskAssessmentDetailed,
    RiskStatistics,
    EconomicIndexBase,
    EconomicIndexCreate,
    EconomicIndexResponse,
    EconomicIndexList,
)

from app.database.schemas.intent import (
    IntentType,
    IntentResult,
    EntityType,
    ExtractedEntity,
    IntentPattern,
)

from app.database.schemas.intent_log import (
    ResponseType,
    ChangeType,
    ImprovementStatus,
    IntentMatchInfo,
    IntentLogBase,
    IntentLogCreate,
    IntentLogResponse,
    IntentLogList,
    IntentLogStats,
    IntentPatternBase,
    IntentPatternCreate,
    IntentPatternUpdate,
    IntentPatternResponse,
    IntentPatternList,
    IntentPatternStats,
    PatternHistoryCreate,
    PatternHistoryResponse,
    PatternImprovementBase,
    PatternImprovementCreate,
    PatternImprovementResponse,
    PatternImprovementList,
    ApplyImprovementRequest,
    PatternAnalysisRequest,
    PatternAnalysisResult,
    DashboardStats,
)

from app.database.schemas.chat import (
    ChatMessage,
    ChatResponseExtended,
    ChatAction,
    ActionType,
)

__all__ = [
    # Knowledge Source
    "KnowledgeSourceBase",
    "KnowledgeSourceCreate",
    "KnowledgeSourceUpdate",
    "KnowledgeSourceResponse",
    "KnowledgeSourceList",
    "KnowledgeChunkResponse",
    "KnowledgeSourceUpload",
    # Document
    "PaymentDocumentBase",
    "PaymentDocumentCreate",
    "PaymentDocumentUpdate",
    "PaymentDocumentResponse",
    "PaymentDocumentList",
    "DocumentUploadResponse",
    "AnalysisResultBase",
    "AnalysisResultCreate",
    "AnalysisResultResponse",
    "DocumentAnalysisRequest",
    "DocumentAnalysisResponse",
    "DocumentListFilters",
    # Compliance
    "ComplianceCheckBase",
    "ComplianceCheckCreate",
    "ComplianceCheckResponse",
    "ComplianceCheckRequest",
    "ComplianceCheckItem",
    "ComplianceCheckResult",
    "ComplianceCheckListResponse",
    "ComplianceKnowledgeBase",
    "ComplianceKnowledgeCreate",
    "ComplianceStatistics",
    # Risk
    "RiskAssessmentBase",
    "RiskAssessmentCreate",
    "RiskAssessmentResponse",
    "RiskAssessmentRequest",
    "RiskFactor",
    "EconomicIndex",
    "RiskAssessmentDetailed",
    "RiskStatistics",
    "EconomicIndexBase",
    "EconomicIndexCreate",
    "EconomicIndexResponse",
    "EconomicIndexList",
    # Intent
    "IntentType",
    "IntentResult",
    "EntityType",
    "ExtractedEntity",
    "IntentPattern",
    # Intent Logs & Patterns
    "ResponseType",
    "ChangeType",
    "ImprovementStatus",
    "IntentMatchInfo",
    "IntentLogBase",
    "IntentLogCreate",
    "IntentLogResponse",
    "IntentLogList",
    "IntentLogStats",
    "IntentPatternBase",
    "IntentPatternCreate",
    "IntentPatternUpdate",
    "IntentPatternResponse",
    "IntentPatternList",
    "IntentPatternStats",
    "PatternHistoryCreate",
    "PatternHistoryResponse",
    "PatternImprovementBase",
    "PatternImprovementCreate",
    "PatternImprovementResponse",
    "PatternImprovementList",
    "ApplyImprovementRequest",
    "PatternAnalysisRequest",
    "PatternAnalysisResult",
    "DashboardStats",
    # Chat
    "ChatMessage",
    "ChatResponseExtended",
    "ChatAction",
    "ActionType",
]
