import type {
  AttachedDocument,
  Counterparty,
  Organization,
  PaymentForm,
  PlatformUser,
  TimelineEntry,
  VedRole,
} from "./types";
import { ROLES } from "./roles";
import { statusMeta, STAGES, stageIndex } from "./statuses";

/** ------------------------------------------------------------------
 * Тестовые данные для ручного прогона интерфейса.
 * Покрывают все 6 ролей и все 9 стадий жизненного цикла заявки.
 * ------------------------------------------------------------------ */

export const ORGANIZATIONS: Organization[] = [
  {
    id: "org-1",
    name: 'ООО "Северный Импорт"',
    inn: "7708123456",
    legalAddress: "г. Москва, ул. Тверская, 12, стр. 3",
    status: "approved",
    rating: "yellow",
    createdAt: "2026-01-14T09:12:00Z",
  },
  {
    id: "org-2",
    name: 'ООО "Балтик Трейд"',
    inn: "7802345671",
    legalAddress: "г. Санкт-Петербург, Лиговский пр., 84",
    status: "waiting_verification",
    createdAt: "2026-05-02T11:40:00Z",
  },
  {
    id: "org-3",
    name: 'АО "Уралмаш-Экспорт"',
    inn: "6659001122",
    legalAddress: "г. Екатеринбург, пр. Ленина, 41",
    status: "approved",
    createdAt: "2025-11-21T07:05:00Z",
  },
  {
    id: "org-4",
    name: 'ООО "Техноснаб Юг"',
    inn: "6162778899",
    legalAddress: "г. Ростов-на-Дону, ул. Береговая, 8",
    status: "not_approved",
    createdAt: "2026-06-18T13:22:00Z",
  },
];

export const COUNTERPARTIES: Counterparty[] = [
  {
    id: "cp-1",
    name: "Shenzhen Kaiyuan Electronics Co., Ltd",
    country: "Китай",
    countryCode: "CN",
    bank: "Bank of China, Shenzhen Branch",
    swift: "BKCHCNBJ45A",
    scope: "foreign",
    status: "approved",
  },
  {
    id: "cp-2",
    name: "Anadolu Makina Sanayi A.Ş.",
    country: "Турция",
    countryCode: "TR",
    bank: "Türkiye İş Bankası",
    swift: "ISBKTRIS",
    scope: "foreign",
    status: "approved",
  },
  {
    id: "cp-3",
    name: "Emirates General Trading LLC",
    country: "ОАЭ",
    countryCode: "AE",
    bank: "Emirates NBD",
    swift: "EBILAEAD",
    scope: "foreign",
    status: "approved",
  },
  {
    id: "cp-4",
    name: "Hanoi Agro Export JSC",
    country: "Вьетнам",
    countryCode: "VN",
    bank: "Vietcombank",
    swift: "BFTVVNVX",
    scope: "foreign",
    status: "not_approved",
  },
  {
    id: "cp-5",
    name: "Almaty Logistics Group TOO",
    country: "Казахстан",
    countryCode: "KZ",
    bank: "Halyk Bank",
    swift: "HSBKKZKX",
    scope: "foreign",
    status: "approved",
  },
];

export const USERS: PlatformUser[] = [
  ...ROLES.map<PlatformUser>((role, i) => ({
    id: `u-seed-${i + 1}`,
    name: role.personName,
    email: role.seedEmail,
    role: role.id,
    organization: role.id === "user" ? ORGANIZATIONS[0]!.name : undefined,
    blocked: false,
    createdAt: "2025-10-01T08:00:00Z",
  })),
  {
    id: "u-7",
    name: "И. Лебедева",
    email: "lebedeva@baltictrade.ru",
    role: "user",
    organization: ORGANIZATIONS[1]!.name,
    blocked: false,
    createdAt: "2026-05-02T11:38:00Z",
  },
  {
    id: "u-8",
    name: "О. Кузнецов",
    email: "kuznetsov@uralmash.ru",
    role: "user",
    organization: ORGANIZATIONS[2]!.name,
    blocked: false,
    createdAt: "2025-11-21T07:02:00Z",
  },
  {
    id: "u-9",
    name: "Р. Салимов",
    email: "salimov@technosnab.ru",
    role: "user",
    organization: ORGANIZATIONS[3]!.name,
    blocked: true,
    createdAt: "2026-06-18T13:20:00Z",
  },
  {
    id: "u-10",
    name: "Н. Верещагина",
    email: "manager2@bdui.local",
    role: "manager",
    blocked: false,
    createdAt: "2026-02-11T09:30:00Z",
  },
  {
    id: "u-11",
    name: "L. Nguyen",
    email: "provider2@bdui.local",
    role: "provider",
    blocked: false,
    createdAt: "2026-03-04T06:15:00Z",
  },
];

const DOC_TEMPLATES: Record<AttachedDocument["kind"], { title: string; ext: AttachedDocument["ext"] }> = {
  invoice: { title: "Инвойс поставщика", ext: "PDF" },
  contract: { title: "Агентский договор", ext: "PDF" },
  order: { title: "Поручение принципала", ext: "PDF" },
  payment: { title: "Платёжное поручение", ext: "PDF" },
  report: { title: "Отчёт агента", ext: "PDF" },
  shipment: { title: "Транспортная накладная", ext: "JPG" },
  other: { title: "Дополнительный документ", ext: "XLSX" },
};

function doc(id: string, kind: AttachedDocument["kind"], at: string, size = "412 КБ"): AttachedDocument {
  return { id, ...DOC_TEMPLATES[kind], kind, size, uploadedAt: at };
}

function line(id: string, title: string, at: string, actorRole: VedRole, done = true): TimelineEntry {
  return { id, title, at, actorRole, done };
}

type Seed = {
  number: string;
  status: string;
  direction: PaymentForm["direction"];
  kind: PaymentForm["kind"];
  condition: PaymentForm["condition"];
  amount: number;
  currency: string;
  org: string;
  cp: string;
  hsCode: string;
  owner: string;
  manager?: string;
  provider?: string;
  reject?: string;
  days: number;
  docs: AttachedDocument["kind"][];
};

/** Каждая строка — сценарий ручного теста для конкретной роли/стадии. */
const SEEDS: Seed[] = [
  {
    number: "ВЭД-2026-0101",
    status: "draft",
    direction: "import",
    kind: "good",
    condition: "advance",
    amount: 4_850_000,
    currency: "CNY",
    org: "org-1",
    cp: "cp-1",
    hsCode: "8542 31 90",
    owner: "Д. Морозов",
    days: 1,
    docs: ["invoice"],
  },
  {
    number: "ВЭД-2026-0102",
    status: "creating",
    direction: "import",
    kind: "good",
    condition: "advance",
    amount: 1_240_000,
    currency: "USD",
    org: "org-1",
    cp: "cp-3",
    hsCode: "8471 30 00",
    owner: "Д. Морозов",
    days: 0,
    docs: ["invoice"],
  },
  {
    number: "ВЭД-2026-0103",
    status: "organization_waiting_verification",
    direction: "import",
    kind: "good",
    condition: "advance",
    amount: 9_600_000,
    currency: "CNY",
    org: "org-2",
    cp: "cp-1",
    hsCode: "8517 62 00",
    owner: "И. Лебедева",
    days: 2,
    docs: ["invoice", "other"],
  },
  {
    number: "ВЭД-2026-0104",
    status: "organization_verification",
    direction: "import",
    kind: "service",
    condition: "postPayment",
    amount: 320_000,
    currency: "AED",
    org: "org-2",
    cp: "cp-3",
    hsCode: "—",
    owner: "И. Лебедева",
    days: 3,
    docs: ["invoice"],
  },
  {
    number: "ВЭД-2026-0105",
    status: "form_waiting_verification",
    direction: "export",
    kind: "good",
    condition: "postPayment",
    amount: 18_400_000,
    currency: "USD",
    org: "org-3",
    cp: "cp-5",
    hsCode: "8474 20 00",
    owner: "О. Кузнецов",
    days: 4,
    docs: ["invoice", "other"],
  },
  {
    number: "ВЭД-2026-0106",
    status: "form_verification",
    direction: "import",
    kind: "good",
    condition: "advance",
    amount: 2_780_000,
    currency: "TRY",
    org: "org-1",
    cp: "cp-2",
    hsCode: "8413 70 21",
    owner: "Д. Морозов",
    days: 5,
    docs: ["invoice"],
  },
  {
    number: "ВЭД-2026-0107",
    status: "form_waiting_corrections",
    direction: "import",
    kind: "good",
    condition: "advance",
    amount: 640_000,
    currency: "USD",
    org: "org-1",
    cp: "cp-4",
    hsCode: "0902 30 00",
    owner: "Д. Морозов",
    reject: "В инвойсе не совпадает сумма с контрактом, приложите приложение №2.",
    days: 6,
    docs: ["invoice"],
  },
  {
    number: "ВЭД-2026-0108",
    status: "form_accepted",
    direction: "import",
    kind: "good",
    condition: "advance",
    amount: 5_100_000,
    currency: "CNY",
    org: "org-1",
    cp: "cp-1",
    hsCode: "8544 42 90",
    owner: "Д. Морозов",
    manager: "П. Иванов",
    days: 7,
    docs: ["invoice"],
  },
  {
    number: "ВЭД-2026-0109",
    status: "contract_waiting",
    direction: "import",
    kind: "good",
    condition: "advance",
    amount: 3_300_000,
    currency: "USD",
    org: "org-3",
    cp: "cp-2",
    hsCode: "7208 51 00",
    owner: "О. Кузнецов",
    manager: "П. Иванов",
    days: 8,
    docs: ["invoice", "contract"],
  },
  {
    number: "ВЭД-2026-0110",
    status: "contract_verification",
    direction: "import",
    kind: "good",
    condition: "advance",
    amount: 760_000,
    currency: "AED",
    org: "org-1",
    cp: "cp-3",
    hsCode: "9018 90 84",
    owner: "Д. Морозов",
    manager: "Н. Верещагина",
    days: 9,
    docs: ["invoice", "contract"],
  },
  {
    number: "ВЭД-2026-0111",
    status: "signing_order",
    direction: "import",
    kind: "good",
    condition: "advance",
    amount: 12_900_000,
    currency: "CNY",
    org: "org-1",
    cp: "cp-1",
    hsCode: "8536 50 80",
    owner: "Д. Морозов",
    manager: "П. Иванов",
    days: 10,
    docs: ["invoice", "contract", "order"],
  },
  {
    number: "ВЭД-2026-0112",
    status: "signing_order_waiting_verification",
    direction: "export",
    kind: "good",
    condition: "postPayment",
    amount: 6_450_000,
    currency: "USD",
    org: "org-3",
    cp: "cp-5",
    hsCode: "4407 11 00",
    owner: "О. Кузнецов",
    manager: "П. Иванов",
    days: 11,
    docs: ["invoice", "contract", "order"],
  },
  {
    number: "ВЭД-2026-0113",
    status: "signing_order_verification",
    direction: "import",
    kind: "service",
    condition: "postPayment",
    amount: 210_000,
    currency: "USD",
    org: "org-1",
    cp: "cp-3",
    hsCode: "—",
    owner: "Д. Морозов",
    manager: "Н. Верещагина",
    days: 12,
    docs: ["invoice", "contract", "order"],
  },
  {
    number: "ВЭД-2026-0114",
    status: "signing_order_accepted",
    direction: "import",
    kind: "good",
    condition: "advance",
    amount: 8_200_000,
    currency: "CNY",
    org: "org-1",
    cp: "cp-1",
    hsCode: "8481 80 81",
    owner: "Д. Морозов",
    manager: "П. Иванов",
    days: 13,
    docs: ["invoice", "contract", "order"],
  },
  {
    number: "ВЭД-2026-0115",
    status: "payment_received",
    direction: "import",
    kind: "good",
    condition: "advance",
    amount: 4_050_000,
    currency: "TRY",
    org: "org-3",
    cp: "cp-2",
    hsCode: "8708 30 91",
    owner: "О. Кузнецов",
    manager: "П. Иванов",
    days: 14,
    docs: ["invoice", "contract", "order", "payment"],
  },
  {
    number: "ВЭД-2026-0116",
    status: "payment_processing",
    direction: "import",
    kind: "good",
    condition: "advance",
    amount: 15_700_000,
    currency: "CNY",
    org: "org-1",
    cp: "cp-1",
    hsCode: "8479 89 97",
    owner: "Д. Морозов",
    manager: "П. Иванов",
    provider: "S. Chen",
    days: 15,
    docs: ["invoice", "contract", "order", "payment"],
  },
  {
    number: "ВЭД-2026-0117",
    status: "manager_checking",
    direction: "import",
    kind: "good",
    condition: "advance",
    amount: 990_000,
    currency: "USD",
    org: "org-1",
    cp: "cp-4",
    hsCode: "2106 90 98",
    owner: "Д. Морозов",
    manager: "Н. Верещагина",
    provider: "L. Nguyen",
    reject: "Банк-корреспондент запросил уточнение назначения платежа.",
    days: 16,
    docs: ["invoice", "contract", "order", "payment"],
  },
  {
    number: "ВЭД-2026-0118",
    status: "payment_sent",
    direction: "import",
    kind: "good",
    condition: "advance",
    amount: 7_350_000,
    currency: "AED",
    org: "org-1",
    cp: "cp-3",
    hsCode: "3926 90 97",
    owner: "Д. Морозов",
    manager: "П. Иванов",
    provider: "S. Chen",
    days: 18,
    docs: ["invoice", "contract", "order", "payment"],
  },
  {
    number: "ВЭД-2026-0119",
    status: "report_waiting",
    direction: "import",
    kind: "good",
    condition: "advance",
    amount: 2_150_000,
    currency: "CNY",
    org: "org-1",
    cp: "cp-1",
    hsCode: "8523 51 90",
    owner: "Д. Морозов",
    manager: "П. Иванов",
    provider: "S. Chen",
    days: 20,
    docs: ["invoice", "contract", "order", "payment", "report"],
  },
  {
    number: "ВЭД-2026-0120",
    status: "report_waiting_verification",
    direction: "export",
    kind: "good",
    condition: "postPayment",
    amount: 21_800_000,
    currency: "USD",
    org: "org-3",
    cp: "cp-5",
    hsCode: "7304 19 00",
    owner: "О. Кузнецов",
    manager: "П. Иванов",
    provider: "S. Chen",
    days: 22,
    docs: ["invoice", "contract", "order", "payment", "report"],
  },
  {
    number: "ВЭД-2026-0121",
    status: "shipment_waiting",
    direction: "import",
    kind: "good",
    condition: "advance",
    amount: 3_940_000,
    currency: "TRY",
    org: "org-1",
    cp: "cp-2",
    hsCode: "6403 99 96",
    owner: "Д. Морозов",
    manager: "Н. Верещагина",
    provider: "S. Chen",
    days: 24,
    docs: ["invoice", "contract", "order", "payment", "report"],
  },
  {
    number: "ВЭД-2026-0122",
    status: "shipment_verification",
    direction: "import",
    kind: "good",
    condition: "advance",
    amount: 5_620_000,
    currency: "CNY",
    org: "org-1",
    cp: "cp-1",
    hsCode: "8418 69 00",
    owner: "Д. Морозов",
    manager: "П. Иванов",
    provider: "S. Chen",
    days: 26,
    docs: ["invoice", "contract", "order", "payment", "report", "shipment"],
  },
  {
    number: "ВЭД-2026-0123",
    status: "completed",
    direction: "import",
    kind: "good",
    condition: "advance",
    amount: 11_450_000,
    currency: "CNY",
    org: "org-1",
    cp: "cp-1",
    hsCode: "8501 52 20",
    owner: "Д. Морозов",
    manager: "П. Иванов",
    provider: "S. Chen",
    days: 40,
    docs: ["invoice", "contract", "order", "payment", "report", "shipment"],
  },
  {
    number: "ВЭД-2026-0124",
    status: "canceled_by_compliance_officer",
    direction: "import",
    kind: "good",
    condition: "advance",
    amount: 1_800_000,
    currency: "USD",
    org: "org-4",
    cp: "cp-4",
    hsCode: "2402 20 90",
    owner: "Р. Салимов",
    reject: "Товар входит в перечень ограничений, платёж невозможен.",
    days: 30,
    docs: ["invoice"],
  },
  {
    number: "ВЭД-2026-0125",
    status: "payment_refund_processing",
    direction: "import",
    kind: "good",
    condition: "advance",
    amount: 2_600_000,
    currency: "USD",
    org: "org-1",
    cp: "cp-4",
    hsCode: "8414 51 00",
    owner: "Д. Морозов",
    manager: "П. Иванов",
    provider: "L. Nguyen",
    days: 28,
    docs: ["invoice", "contract", "order", "payment"],
  },
  {
    number: "ВЭД-2026-0126",
    status: "advance_signing_order",
    direction: "import",
    kind: "good",
    condition: "advance",
    amount: 1_150_000,
    currency: "CNY",
    org: "org-1",
    cp: "cp-1",
    hsCode: "8531 20 40",
    owner: "Д. Морозов",
    manager: "П. Иванов",
    days: 17,
    docs: ["invoice", "contract", "order"],
  },
];

const DAY = 86_400_000;
const NOW = Date.UTC(2026, 7, 26, 8, 0, 0);

function iso(daysAgo: number, hourShift = 0): string {
  return new Date(NOW - daysAgo * DAY + hourShift * 3_600_000).toISOString();
}

/** Хронология собирается по стадиям: всё, что до текущей стадии, — выполнено. */
function buildTimeline(status: string, seed: Seed): TimelineEntry[] {
  const current = stageIndex(statusMeta(status).stage);
  const actorByStage: Record<string, VedRole> = {
    new: "user",
    organization_verification: "internal_compliance_officer",
    form_verification: "compliance_officer",
    agency_contract: "manager",
    signing_order: "manager",
    payment: "provider",
    agent_report: "manager",
    shipment: "manager",
    completed: "manager",
  };
  return STAGES.map((stage, i) =>
    line(
      `${seed.number}-tl-${stage.id}`,
      stage.label,
      iso(seed.days - i * 0.4),
      actorByStage[stage.id] ?? "manager",
      i < current || (i === current && statusMeta(status).tone === "done"),
    ),
  );
}

export const FORMS: PaymentForm[] = SEEDS.map((seed, i) => ({
  id: `form-${i + 1}`,
  number: seed.number,
  status: seed.status,
  direction: seed.direction,
  kind: seed.kind,
  condition: seed.condition,
  amountMinor: seed.amount * 100,
  currency: seed.currency,
  organizationId: seed.org,
  counterpartyId: seed.cp,
  hsCode: seed.hsCode,
  invoiceNumber: `INV-${2026}-${(4100 + i).toString()}`,
  ownerName: seed.owner,
  managerName: seed.manager,
  providerName: seed.provider,
  rejectText: seed.reject,
  createdAt: iso(seed.days),
  updatedAt: iso(Math.max(0, seed.days - 1), 3),
  documents: seed.docs.map((kind, k) => doc(`form-${i + 1}-doc-${k}`, kind, iso(seed.days - k * 0.5))),
  timeline: buildTimeline(seed.status, seed),
}));

export function orgById(id: string): Organization | undefined {
  return ORGANIZATIONS.find((o) => o.id === id);
}

export function cpById(id: string): Counterparty | undefined {
  return COUNTERPARTIES.find((c) => c.id === id);
}
