import type {
  ComplianceToolRecord,
  CountryRecord,
  CurrencyRecord,
  HsCodeRecord,
  ProviderRecord,
} from "./reference";

const PROVIDER_NAMES = [
  "Sunrise Payments Ltd",
  "Bosphorus Settlement",
  "Gulf Transfer DMCC",
  "Central Asia Clearing",
  "Nordic Bridge FX",
  "Pacific Rim Settlements",
  "EuroGate Partners",
  "Silk Road Treasury",
  "Atlantic Remit Co",
  "MENA Exchange Hub",
  "Baltic Pay Network",
  "Andes Trade Finance",
  "Sahel Clearing House",
  "Indo-Pacific Payments",
  "Scandinavia FX Desk",
  "Maghreb Settlement",
  "Caspian Transfer AG",
  "Alpine Cross-Border",
  "Rhine Payment Services",
  "Volga Export Desk",
  "Siberia Trade Link",
  "Caucasus Remit Ltd",
  "Black Sea Clearing",
  "Danube Settlement",
  "Adriatic Pay Co",
  "Iberia Trade Bridge",
  "Benelux FX Partners",
  "Carpathian Payments",
  "Arctic Route Finance",
  "Steppe Global Pay",
  "Horizon Trade Desk",
  "Vertex Settlement",
];

const COUNTRY_DATA: Array<[string, string, CountryRecord["risk"]]> = [
  ["CN", "Китай", "low"],
  ["TR", "Турция", "medium"],
  ["AE", "ОАЭ", "low"],
  ["VN", "Вьетнам", "medium"],
  ["KZ", "Казахстан", "low"],
  ["IR", "Иран", "high"],
  ["IN", "Индия", "medium"],
  ["KR", "Южная Корея", "low"],
  ["JP", "Япония", "low"],
  ["TH", "Таиланд", "medium"],
  ["MY", "Малайзия", "low"],
  ["ID", "Индонезия", "medium"],
  ["SG", "Сингапур", "low"],
  ["HK", "Гонконг", "low"],
  ["TW", "Тайвань", "medium"],
  ["DE", "Германия", "low"],
  ["IT", "Италия", "low"],
  ["FR", "Франция", "low"],
  ["ES", "Испания", "low"],
  ["GB", "Великобритания", "low"],
  ["US", "США", "medium"],
  ["CA", "Канада", "low"],
  ["BR", "Бrazil", "medium"],
  ["MX", "Мексика", "medium"],
  ["ZA", "ЮАР", "medium"],
  ["EG", "Египет", "high"],
  ["SA", "Сaudi Arabia", "medium"],
  ["QA", "Кatar", "low"],
  ["KW", "Кувейт", "medium"],
  ["OM", "Оman", "low"],
  ["UZ", "Узбекistan", "medium"],
  ["BY", "Бelarus", "high"],
];

const CURRENCY_CODES = [
  ["USD", "Доллар США", "81,40 ₽", "active"],
  ["CNY", "Юань", "11,25 ₽", "active"],
  ["AED", "Дирхам ОАЭ", "22,16 ₽", "active"],
  ["TRY", "Турецкая лира", "2,04 ₽", "restricted"],
  ["EUR", "Евро", "94,80 ₽", "active"],
  ["KZT", "Тенге", "0,17 ₽", "restricted"],
  ["GBP", "Фунт стерлингов", "108,20 ₽", "active"],
  ["JPY", "Иена", "0,54 ₽", "active"],
  ["CHF", "Швейцарский франк", "92,10 ₽", "active"],
  ["HKD", "Гонконгский доллар", "10,42 ₽", "active"],
  ["SGD", "Сингапурский доллар", "60,30 ₽", "active"],
  ["INR", "Индийская рупия", "0,97 ₽", "restricted"],
  ["KRW", "Южнокорейская вона", "0,06 ₽", "active"],
  ["THB", "Тайский бат", "2,35 ₽", "active"],
  ["VND", "Вьетнамский дong", "0,003 ₽", "restricted"],
  ["MYR", "Малайзийский ringgit", "18,20 ₽", "active"],
  ["IDR", "Индонезийская rupiah", "0,005 ₽", "restricted"],
  ["SAR", "Saudi riyal", "21,70 ₽", "active"],
  ["QAR", "Кatar riyal", "22,30 ₽", "active"],
  ["KWD", "Kuwaiti dinar", "265,00 ₽", "active"],
  ["BRL", "Brazilian real", "14,80 ₽", "restricted"],
  ["MXN", "Mexican peso", "4,20 ₽", "active"],
  ["ZAR", "South African rand", "4,50 ₽", "restricted"],
  ["PLN", "Polish zloty", "20,10 ₽", "active"],
  ["CZK", "Czech koruna", "3,55 ₽", "active"],
  ["HUF", "Hungarian forint", "0,22 ₽", "active"],
  ["RON", "Romanian leu", "18,00 ₽", "active"],
  ["SEK", "Swedish krona", "7,80 ₽", "active"],
  ["NOK", "Norwegian krone", "7,50 ₽", "active"],
  ["DKK", "Danish krone", "12,70 ₽", "active"],
  ["ILS", "Israeli shekel", "22,40 ₽", "restricted"],
  ["EGP", "Egyptian pound", "1,65 ₽", "restricted"],
] as const;

const HS_TITLES = [
  "Вычислительная техника портативная",
  "Оборудование связи",
  "Экскаваторы полноповоротные",
  "Чай чёрный фасованный",
  "Лекарственные средства",
  "Металлоконструкции",
  "Насосы центробежные",
  "Трансформаторы силовые",
  "Кабель силовой",
  "Автомобили легковые",
  "Шины пневматические",
  "Мебель офисная",
  "Текстиль хлопчатобумажный",
  "Обувь кожаная",
  "Косметические средства",
  "Парфюмерные изделия",
  "Пластмассы в первичных формах",
  "Химические реактивы",
  "Удобрения минеральные",
  "Зерно пшеница",
  "Масло подсолнечное",
  "Мясо птицы",
  "Рыба мороженая",
  "Молоко сухое",
  "Сахар белый",
  "Кофе жареный",
  "Какао-порошок",
  "Древесина пиломатериалы",
  "Бумага офисная",
  "Картон гофрированный",
  "Стекло листовое",
  "Керамическая плитка",
];

const COMPLIANCE_TEMPLATES: Array<[string, string, ComplianceToolRecord["scope"]]> = [
  ["DOC-INVOICE", "Некорректный инвойс", "form"],
  ["DOC-CONTRACT", "Нет внешнеторгового контракта", "form"],
  ["DOC-ORDER", "Поручение без подписи", "form"],
  ["DOC-PAYMENT", "Платёжное поручение не читается", "form"],
  ["DOC-REPORT", "Отчёт агента неполный", "form"],
  ["DOC-SHIPMENT", "Документы отгрузки неполные", "form"],
  ["ORG-INN", "ИНН не совпадает с выпиской", "organization"],
  ["ORG-ADDR", "Адрес не подтверждён", "organization"],
  ["ORG-BEN", "Бенефициар не раскрыт", "organization"],
  ["ORG-UBO", "Конечный бенефициар не указан", "organization"],
  ["ORG-LIC", "Лицензия просрочена", "organization"],
  ["ORG-SAN", "Sanctions screening required", "both"],
  ["CP-BANK", "Реквизиты банка неполные", "form"],
  ["CP-COUNTRY", "Страна контрагента high-risk", "form"],
  ["CP-NAME", "Наименование не совпадает с контрактом", "form"],
  ["AML-PEP", "PEP check required", "both"],
  ["AML-SOF", "Источник средств не подтверждён", "form"],
  ["AML-THR", "Подозрительная структура сделки", "form"],
  ["TRADE-HS", "Код ТН ВЭД требует лицензии", "form"],
  ["TRADE-DUAL", "Dual-use goods check", "form"],
  ["TRADE-ORIG", "Страна происхождения не указана", "form"],
  ["FX-RATE", "Курс не согласован", "form"],
  ["FX-LIMIT", "Превышен лимит операции", "form"],
  ["KYC-ID", "Документ удостоверения личности", "organization"],
  ["KYC-POA", "Доверенность не приложена", "organization"],
  ["TAX-VAT", "НДС не выделен в инвойсе", "form"],
  ["TAX-CUST", "Таможенная стоимость не обоснована", "form"],
  ["LOG-INCOT", "Incoterms не указаны", "form"],
  ["LOG-DELIV", "Срок поставки не совпадает", "form"],
  ["LEGAL-SIGN", "Подпись не соответствует доверенности", "both"],
  ["LEGAL-SEAL", "Печать отсутствует", "form"],
  ["OTHER-MISC", "Прочее замечание комплаенс", "both"],
];

export function buildProviderSeed(): ProviderRecord[] {
  const countries = ["Гонконг", "Турция", "ОАЭ", "Казахстан", "Китай", "Сингапур", "Великобритания", "Германия"];
  const corridors = ["USD", "CNY", "EUR", "AED", "TRY", "KZT", "GBP", "JPY"];
  return PROVIDER_NAMES.map((name, i) => ({
    id: `pr-${i + 1}`,
    name,
    country: countries[i % countries.length]!,
    corridors: `${corridors[i % corridors.length]}, ${corridors[(i + 1) % corridors.length]}`,
    contact: `ops${i + 1}@provider.example`,
    slaHours: 18 + (i % 5) * 6,
    status: i % 11 === 0 ? "paused" : "active",
  }));
}

export function buildCountrySeed(): CountryRecord[] {
  return COUNTRY_DATA.map(([code, title, risk]) => ({ code, title, risk }));
}

export function buildCurrencySeed(): CurrencyRecord[] {
  return CURRENCY_CODES.map(([code, title, rate, status]) => ({
    code,
    title,
    rate,
    status: status as CurrencyRecord["status"],
  }));
}

export function buildHsCodeSeed(): HsCodeRecord[] {
  return HS_TITLES.map((title, i) => ({
    code: `${8471000000 + i * 111111}`.slice(0, 10),
    title,
    duty: `${(i % 8) * 2.5} %`,
    license: i % 5 === 0,
  }));
}

export function buildComplianceToolSeed(): ComplianceToolRecord[] {
  return COMPLIANCE_TEMPLATES.map(([code, title, scope], i) => ({
    id: `ct-${i + 1}`,
    code,
    title,
    instruction: `Исправьте: ${title.toLowerCase()}. Приложите документы или уточните данные.`,
    scope,
    active: i % 9 !== 0,
  }));
}
