#!/bin/bash

# Полный backup системы AMG Flow
# Автор: AMG Flow Team
# Версия: 1.0

set -e  # Остановить выполнение при ошибке

# Цвета для вывода
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Конфигурация
BACKUP_DIR="backups/full"
TIMESTAMP=$(date +"%Y%m%d_%H%M%S")
BACKUP_NAME="amg_flow_backup_${TIMESTAMP}"

echo -e "${BLUE}🚀 Запуск полного backup системы AMG Flow...${NC}"
echo -e "${YELLOW}📅 Время: $(date)${NC}"
echo -e "${YELLOW}📁 Директория: $BACKUP_DIR${NC}"

# Создаем директорию для backup
mkdir -p "$BACKUP_DIR/$BACKUP_NAME"

echo -e "${BLUE}📋 Создаем полный backup системы...${NC}"

# 1. Backup базы данных
echo -e "${BLUE}1️⃣ Backup базы данных...${NC}"
if [ -f "scripts/backup_database.sh" ]; then
    bash scripts/backup_database.sh
    # Копируем последний backup базы данных
    cp backups/database/latest.sql.gz "$BACKUP_DIR/$BACKUP_NAME/database.sql.gz"
    echo -e "${GREEN}✅ Backup базы данных скопирован${NC}"
else
    echo -e "${YELLOW}⚠️  Скрипт backup базы данных не найден${NC}"
fi

# 2. Backup моделей Ollama
echo -e "${BLUE}2️⃣ Backup моделей Ollama...${NC}"
if [ -f "scripts/backup_models.sh" ]; then
    bash scripts/backup_models.sh
    # Копируем backup моделей
    cp -r models/backup "$BACKUP_DIR/$BACKUP_NAME/ollama_models"
    echo -e "${GREEN}✅ Backup моделей скопирован${NC}"
else
    echo -e "${YELLOW}⚠️  Скрипт backup моделей не найден${NC}"
fi

# 3. Backup конфигурационных файлов
echo -e "${BLUE}3️⃣ Backup конфигурационных файлов...${NC}"
mkdir -p "$BACKUP_DIR/$BACKUP_NAME/config"
cp docker-compose.yml "$BACKUP_DIR/$BACKUP_NAME/config/" 2>/dev/null || true
cp docker-compose.*.yml "$BACKUP_DIR/$BACKUP_NAME/config/" 2>/dev/null || true
cp .env* "$BACKUP_DIR/$BACKUP_NAME/config/" 2>/dev/null || true
cp pyproject.toml "$BACKUP_DIR/$BACKUP_NAME/config/" 2>/dev/null || true
cp alembic.ini "$BACKUP_DIR/$BACKUP_NAME/config/" 2>/dev/null || true
echo -e "${GREEN}✅ Конфигурационные файлы скопированы${NC}"

# 4. Backup исходного кода (без node_modules и .venv)
echo -e "${BLUE}4️⃣ Backup исходного кода...${NC}"
mkdir -p "$BACKUP_DIR/$BACKUP_NAME/source"
rsync -av --exclude='node_modules' --exclude='.venv' --exclude='__pycache__' --exclude='*.pyc' --exclude='.git' --exclude='backups' . "$BACKUP_DIR/$BACKUP_NAME/source/"
echo -e "${GREEN}✅ Исходный код скопирован${NC}"

# 5. Backup логов (если есть)
echo -e "${BLUE}5️⃣ Backup логов...${NC}"
if [ -d "logs" ]; then
    cp -r logs "$BACKUP_DIR/$BACKUP_NAME/"
    echo -e "${GREEN}✅ Логи скопированы${NC}"
else
    echo -e "${YELLOW}⚠️  Директория логов не найдена${NC}"
fi

# 6. Создаем информацию о backup
echo -e "${BLUE}6️⃣ Создаем информацию о backup...${NC}"
cat > "$BACKUP_DIR/$BACKUP_NAME/backup_info.txt" << EOF
AMG Flow Backup Information
==========================
Backup Date: $(date)
Backup Type: Full System Backup
System Version: 0.1.0

Contents:
- database.sql.gz: PostgreSQL database backup
- ollama_models/: Ollama models backup
- config/: Configuration files
- source/: Source code (excluding dependencies)
- logs/: Application logs (if available)

Restore Instructions:
1. Extract this backup to a clean directory
2. Run: bash scripts/restore_database.sh latest
3. Run: docker compose up -d
4. Run: bash scripts/model_pull.sh (to restore models)

Generated by: AMG Flow Backup System v1.0
EOF
echo -e "${GREEN}✅ Информация о backup создана${NC}"

# 7. Создаем архив
echo -e "${BLUE}7️⃣ Создаем архив...${NC}"
cd "$BACKUP_DIR"
tar -czf "${BACKUP_NAME}.tar.gz" "$BACKUP_NAME"
cd - > /dev/null

# Показываем статистику
ARCHIVE_SIZE=$(du -h "$BACKUP_DIR/${BACKUP_NAME}.tar.gz" | cut -f1)
echo -e "${GREEN}✅ Архив создан: $BACKUP_DIR/${BACKUP_NAME}.tar.gz (размер: $ARCHIVE_SIZE)${NC}"

# Создаем симлинк на последний backup
ln -sf "${BACKUP_NAME}.tar.gz" "$BACKUP_DIR/latest.tar.gz"
echo -e "${GREEN}🔗 Создан симлинк на последний backup${NC}"

# Очищаем временные файлы
rm -rf "$BACKUP_DIR/$BACKUP_NAME"
echo -e "${GREEN}🧹 Временные файлы очищены${NC}"

# Показываем статистику
echo -e "${BLUE}📊 Статистика backup директории:${NC}"
ls -lah "$BACKUP_DIR"

echo -e "${GREEN}🎉 Полный backup системы завершен успешно!${NC}"
echo -e "${YELLOW}💡 Архив: $BACKUP_DIR/${BACKUP_NAME}.tar.gz${NC}"
echo -e "${YELLOW}💡 Для восстановления: tar -xzf $BACKUP_DIR/latest.tar.gz${NC}"
